language: generic

sudo: required

services:
  - docker

before_install: # test script 수행을 위한 준비
  - docker build -t arhrina/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true arhrina/react-test-app npm run test

after success:
  - docker build -t arhrina/docker-frontend    ./frontend
  - docker build -t arhrina/docker-backend     ./backend
  - docker build -t arhrina/nginx              ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin # 도커허브 로그인하는 정보값을 환경변수로 지정. Travis CI more option-settings에 Environment Variables에 환경변수 추가

  - docker push arhrina/docker-frontend
  - docker push arhrina/docker-backend
  - docker push arhrina/nginx

deploy:
  provider: elasticbeanstalk # 외부 서비스 표시
  region: "ap-northeast-2" # AWS의 물리적 위치. URL에 존재
  app: "docker-fullstack-app"
  env: Dockerfullstackapp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-116047828143
  bucket_path: "docker-fullstack-app"

  on:
    branch: master
